server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: monolith-auth
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                    key-resolver: "#{@ipKeyResolver}"

            - id: chat-service
              uri: http://localhost:8082
              predicates:
                - Path=/ws/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 40
                    key-resolver: "#{@ipKeyResolver}"