# ==========================================
# 1. CONFIGURACIÓN DEL SERVIDOR
# ==========================================
# El monolito corre en 8080/8081, este microservicio correrá en 8082
server.port=8082
spring.application.name=tesla-social-service

# ==========================================
# 2. CONFIGURACIÓN DE BASE DE DATOS INDEPENDIENTE
# ==========================================
# Nota el cambio en la URL: Ahora apunta a una BD llamada 'tesla_social_db'
# Usamos variables de entorno con un valor por defecto local para que no falle al iniciar
spring.datasource.url=jdbc:postgresql://ep-gentle-leaf-anbs8osh-pooler.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_QKrsn6Gq0lvZ&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QKrsn6Gq0lvZ
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# 3. CONFIGURACIÓN DE HIBERNATE (Generación de Tablas)
# ==========================================
# 'update' creará las tablas (grupos, grupo_miembros, chat_messages) automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false